export const menuItems = [
  {
    name: "solutions",
    label: "Solutions",
    items: [
      { name: "solutions/consulting", label: "Cost Consulting" },
      { name: "solutions/forensics", label: "Change Forensics" },
      { name: "solutions/analytics", label: "Cost Analytics Solutions" },
      { name: "solutions/research", label: "Market Research" },
      { name: "solutions/claims", label: "Claims Assistance" },
      { name: "solutions/legal", label: "Legal Services" },
    ],
  },
  {
    name: "services",
    label: "Services",
    items: [
      { name: "services/takeoff", label: "Takeoff / Survey" },
      { name: "services/estimating", label: "Estimating & Modeling" },
      { name: "services/procurement", label: "Procurement" },
      { name: "services/reconciliation", label: "Cost Reconciliation" },
      { name: "services/controls", label: "Cost Controls" },
    ],
  },
  {
    name: "markets",
    label: "Markets",
    items: [
      { name: "markets/airport", label: "Airport / Terminal" },
      { name: "markets/corporate", label: "Corporate" },
      { name: "markets/data-centers", label: "Mission Critical" },
      { name: "markets/high-rise", label: "High-Rise / Mixed Use" },
      { name: "markets/hospitality", label: "Hotels / Hospitality" },
      { name: "markets/industrial", label: "Industrial" },
      { name: "markets/residential", label: "Residential" },
      { name: "markets/medical", label: "Medical / OSHPD" },
      { name: "markets/labs", label: "Labs / Life-Sciences" },
    ],
  },
  {
    name: "expertise",
    label: "Expertise",
    items: [
      { name: "expertise/mechanical", label: "Mechanical / HVAC" },
      { name: "expertise/plumbing", label: "Plumbing & Sprinkler" },
      { name: "expertise/electrical", label: "Electrical Systems" },
      { name: "expertise/life-safety", label: "Fire & Life Safety" },
      { name: "expertise/technology", label: "Network / IT" },
      { name: "expertise/technology", label: "Voice / Audio Visual" },
      { name: "expertise/technology", label: "Security & Access" },
      { name: "expertise/technology", label: "Wireless / RF" },
    ],
  },
  {
    name: "company",
    label: "Company",
    items: [
      { name: "company/data-centers", label: "Our Approach" },
      { name: "company/data-centers", label: "EstiBase™ Platform" },
      { name: "company/corporate", label: "Our Team" },
      { name: "company/data-centers", label: "Careers" },
      { name: "company/data-centers", label: "Contact Us" },
    ],
  },
];
